const ACTION = {
  SET_EMAIL_REQUESTED: 'SET_EMAIL_REQUESTED',
  SET_PASSWORD_REQUESTED: 'SET_PASSWORD_REQUESTED',
  SET_EMAIL_SUCCESS: 'SET_EMAIL_SUCCESS',
  SET_PASSWORD_SUCCESS: 'SET_PASSWORD_SUCCESS',
  SET_LIST_HOME_PAGE: 'SET_LIST_HOME_PAGE',
  SET_LIST_REQUESTED: 'SET_LIST_REQUESTED',
  SET_DETAIL_REQUESTED: 'SET_DETAIL_REQUESTED',
  SET_DETAIL_PAGE: 'SET_DETAIL_PAGE',
  SET_VISIBILITY: 'SET_VISIBILITY',
  SHOW_FORM_STAR: 'SHOW_FORM_STAR',
  REGISTERED_REQUESTED: 'REGISTERED_REQUESTED',
  REGISTERED_SUCCESS: 'REGISTERED_SUCCESS',
  REGISTERED_FAILED: 'REGISTERED_FAILED',
  LOGIN_REQUESTED: 'LOGIN_REQESTED',
};

export default ACTION;
